//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Opration_product.Data_Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Product
    {
        public int Product_id { get; set; }
        public string product_Name { get; set; }
        public Nullable<int> categeory_id { get; set; }
    }
}
