//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Opration_product.Data_Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Db_Product_Crud_OperationEntities : DbContext
    {
        public Db_Product_Crud_OperationEntities()
            : base("name=Db_Product_Crud_OperationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_Categeory> M_Categeory { get; set; }
        public virtual DbSet<M_Product> M_Product { get; set; }
    
        public virtual ObjectResult<Sp_Crud_Result> Sp_Crud()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Crud_Result>("Sp_Crud");
        }
    }
}
